# Generated by Django 4.2 on 2023-09-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testname', models.CharField(max_length=50, null=True)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='testresults',
            name='name',
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n1',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n2',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n3',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n4',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n5',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n6',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TestNames',
        ),
    ]
