# Generated by Django 4.2 on 2023-09-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testnames',
            name='name',
        ),
    ]
