# Generated by Django 4.2 on 2023-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_reports_remove_testresults_name_testcategories_n1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='image',
            new_name='file',
        ),
    ]
