# Generated by Django 4.2 on 2023-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_remove_testnames_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresults',
            name='name',
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcategories',
            name='n6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TestNames',
        ),
    ]
