# Generated by Django 4.2 on 2023-09-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_remove_testresults_name_testcategories_n1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresults',
            name='n1',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n2',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n3',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n4',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n5',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testresults',
            name='n6',
            field=models.CharField(blank=True, default='Null', max_length=50, null=True),
        ),
    ]
